Poetry and docker-compose (#9)
Convert project structure to be able to build it with poetry. Add docker-compose to github actions workflow.

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -19,28 +19,24 @@ jobs:
       checks: write
     steps:
       - uses: actions/checkout@v3
-      - name: Set up Python 3.11
-        uses: actions/setup-python@v3
-        with:
-          python-version: "3.11"
-      - name: Install dependencies
+      - name: Check code formatting with Black
         run: |
-          python -m pip install --upgrade pip
-          pip install flake8 pytest
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          docker-compose -f compose.test.yaml up --exit-code-from format format
+          exit $?
       - name: Lint with flake8
+        if: success() || failure() # always run even if the previous step fails
         run: |
-          # stop the build if there are Python syntax errors or undefined names
-          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+          docker-compose -f compose.test.yaml up --exit-code-from lint lint
+          exit $?
       - name: Test with pytest
+        if: success() || failure()
         run: |
-          python -m pytest --verbose --junit-xml=junit.xml
+          docker-compose -f compose.test.yaml up --exit-code-from test test
+          exit $?
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure() # always run even if the previous step fails
+        if: success() || failure()
         with:
-          report_paths: "**/junit.xml"
+          report_paths: "**/test_results/junit.xml"
           detailed_summary: true
           include_passed: true
