checking workflow steps exit codes

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -24,14 +24,18 @@ jobs:
           docker-compose -f compose.test.yaml up --exit-code-from format format
           exit $?
       - name: Lint with flake8
+        if: success() || failure() # always run even if the previous step fails
         run: |
-          docker-compose -f compose.test.yaml up lint
+          docker-compose -f compose.test.yaml up --exit-code-from lint lint
+          exit $?
       - name: Test with pytest
+        if: success() || failure()
         run: |
-          docker-compose -f compose.test.yaml up test
+          docker-compose -f compose.test.yaml up --exit-code-from test test
+          exit $?
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure() # always run even if the previous step fails
+        if: success() || failure()
         with:
           report_paths: "**/test_results/junit.xml"
           detailed_summary: true
